package com.linkbit.mvp.domain;

public enum LedgerEntryType {
    FIAT_DISBURSEMENT,
    BORROWER_REPAYMENT,
    INTEREST_ACCRUAL,
    COLLATERAL_RELEASE,
    COLLATERAL_TOPUP,
    LIQUIDATION_EXECUTED,
    LENDER_REPAID,
    LIQUIDATION_PENALTY,
    BORROWER_COLLATERAL_RETURN,
    COLLATERAL_RELEASED,
    ESCROW_CLOSED
}
