package com.linkbit.mvp.domain;

public enum LoanAction {
    FINALIZE_CONTRACT,
    SIGN_CONTRACT,
    CANCEL_NEGOTIATION,
    PAY_FEE,
    DEPOSIT_COLLATERAL,
    DISBURSE_FIAT,
    MARK_DISPUTE,
    RESOLVE_DISPUTE,
    LTV_DROP_MARGIN_CALL,
    LTV_DROP_LIQUIDATION,
    LTV_RECOVERED,
    EXECUTE_LIQUIDATION,
    REPAY_LOAN,
    RELEASE_COLLATERAL,
    ADMIN_OVERRIDE
}
